// <auto-generated />
namespace Enterprise_Program_Benefits.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class software : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(software));
        
        string IMigrationMetadata.Id
        {
            get { return "201610260646273_software"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
